### ISSUE TITLE
Can't yield from root fiber

### ISSUE THREAD

**Issue by theonegri** [splitrb/split#261]
So, I'm trying ton implement the gem on our app but I'm getting a can't yield from root fiber error:
```ruby
ActionView::Template::Error (can't yield from root fiber):
    8: 			</li>
    9: 			<li class="divider"></li>
    10: 			<li>
    11: 					<% ab_test("service_request_class", "testtestetst", "signup-modal") do |sr_class| %>
    12: 						<%= link_to new_service_request_url, class: sr_class do %>
    13: 					  		<span class="glyphicon glyphicon-cog"></span>Get multiple bids
    14: 						<% end %>
  app/views/layouts/_navbar_right.html.erb:11:in `_app_views_layouts__navbar_right_html_erb__2555705106050273440_70352337199200'
  app/views/layouts/_responsive_nav.html.erb:25:in `_app_views_layouts__responsive_nav_html_erb__4011861569669617519_70352337174120'
  app/views/layouts/search.html.erb:17:in `_app_views_layouts_search_html_erb___3678773959418380084_70352319762880'


  Rendered /Users/theonegri/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.18/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
  Rendered /Users/theonegri/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.18/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
  Rendered /Users/theonegri/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.18/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (13.1ms)
Exiting
```

So I changed my code and added ```Fiber.new```:
```ruby
<li>
	<% Fiber.new{ %>
		<% ab_test("service_request_class", "testtestetst", "signup-modal") do |sr_class| %>
			<%= link_to new_service_request_url, class: sr_class do %>
				<span class="glyphicon glyphicon-cog"></span>Get multiple bids
			<% end %>
		<% end %>
	<% }.resume %>
</li>
```
But now I'm getting this error:
```ruby
Exiting
/Users/theonegri/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-3.2.18/lib/action_view/helpers/text_helper.rb:52:in `concat': undefined method `<<' for nil:NilClass (NoMethodError)
	from /Users/theonegri/.rvm/gems/ruby-2.0.0-p247/gems/split-0.7.2/lib/split/helper.rb:44:in `ab_test'
	from /Users/theonegri/Work/buildzoom/rails/app/views/layouts/_navbar_right.html.erb:12:in `block in _app_views_layouts__navbar_right_html_erb__2911523060393528697_70112438978940'
```

I'm not sure what do do/how to fix that

**Comment by andrew** [comment]
Closing as this issue is over 2 years old, please reopen if it's still affecting you.
