### ISSUE TITLE
Uninitialized constant Split::Redis without explicit require of redis-namespace gem

### ISSUE THREAD

**Issue by joffotron** [splitrb/split#463]
Hi!

We upgraded our app from split 2.1 -> 2.2, and now on the dashboard page, and on pages that call e.g. `ab_test` we get an `Uninitialized constant Split::Redis` error.

This can be fixed by manually re-introducing the `redis-namespace` gem into our Gemfile.

### Attached is our Gemfile / .lock:

<details>
<summary>Gemfile</summary>

```
source "https://rubygems.org"

gem "rails", "5.0.0.1"
gem "rack-cors", "~> 0.4.0"

gem 'puma', '3.6.2'

gem "pg", "~> 0.15"

gem "sass-rails", "~> 5.0"
gem 'uglifier', '3.0.4'
gem "therubyracer", platforms: :ruby
gem "bcrypt", "~> 3.1.7"

gem "devise", "~> 4.2"
gem "pundit", "~> 1.1"
gem 'gaffe', '~> 1.2'
gem 'rack-utm_cookies', git: 'https://github.com/joshuapaling/rack-utm_cookies'

gem 'remotipart', git: 'https://github.com/mshibuya/remotipart.git' 
gem 'rails_admin', '1.1.0'
gem 'attribute_normalizer', '~> 1.2'
gem 'acts_as_list', '~> 0.8.2'

gem "redcarpet", "~> 3.3", ">= 3.3.4"
gem "paper_trail", "~> 4.1"

gem "mini_magick", "~> 4.5", ">= 4.5.1"
gem "carrierwave", "~> 0.11.0"
gem "fog", "~> 1.38"

gem 'aws-sdk', '2.6.30', require: false
gem "retries", "~> 0.0.5", require: false

gem 'friendly_id', '5.2.0'
gem "money-rails", "~> 1.7"

gem "doorkeeper", "~> 4.1"

gem 'rollbar', '2.13.3'

gem 'sinatra', '~> 2.0.0.beta2'
gem 'split', '~> 2.2.0', require: 'split/dashboard'
gem 'redis-namespace', '1.5.2'

gem 'react_on_rails', '6.2.1'
gem 'graphql', '1.2.5'
gem 'graphiql-rails', '1.4'
gem 'graphql-client', '~> 0.3.0', require: false

group :development do
  gem 'web-console', '3.3.1'
  gem "spring"
end

group :development, :test do
  gem "byebug"
  gem "spring-commands-rspec", "~> 1.0", ">= 1.0.4"
  gem 'rspec-rails', '3.5.2'
  gem "guard-rspec", "~> 4.6", ">= 4.6.5"
  gem 'awesome_print'
end

group :test do
  gem "faker", "~> 1.6", ">= 1.6.3"
  gem "factory_girl_rails", "~> 4.6"
  gem 'with_model', git: 'https://github.com/Casecommons/with_model.git', branch: 'master'
  gem 'rspec-mocks', '~> 3.5'
  gem 'capybara', '2.10.0'
  gem 'simplecov', '0.12.0', require: false
  gem "oauth2", "~> 1.1"
  gem "rails-controller-testing", "~> 1.0", ">= 1.0.1"
end
```

</details>

<details>
<summary>Gemfile.lock</summary>

```
GIT
  remote: https://github.com/Casecommons/with_model.git
  revision: b34859740f0046da50905c420a1011059ce11179
  branch: master
  specs:
    with_model (1.2.1)
      activerecord (>= 3.0)

GIT
  remote: https://github.com/joshuapaling/rack-utm_cookies
  revision: 46ed7f9d640c78a2bad20011ecd13d4252f4300b
  specs:
    rack-utm_cookies (0.1.2)
      rack

GIT
  remote: https://github.com/mshibuya/remotipart.git
  revision: 7e244e78e148430b7720e6cf8f86263d6a1dfddf
  specs:
    remotipart (1.3.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.3)
    actioncable (5.0.0.1)
      actionpack (= 5.0.0.1)
      nio4r (~> 1.2)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.0.1)
      actionview (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.0.1)
      activesupport (= 5.0.0.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (5.0.0.1)
      activesupport (= 5.0.0.1)
      globalid (>= 0.3.6)
    activemodel (5.0.0.1)
      activesupport (= 5.0.0.1)
    activerecord (5.0.0.1)
      activemodel (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      arel (~> 7.0)
    activesupport (5.0.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    acts_as_list (0.8.2)
      activerecord (>= 3.0)
    addressable (2.4.0)
    arel (7.1.2)
    attribute_normalizer (1.2.0)
    awesome_print (1.7.0)
    aws-sdk (2.6.30)
      aws-sdk-resources (= 2.6.30)
    aws-sdk-core (2.6.30)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.6.30)
      aws-sdk-core (= 2.6.30)
    aws-sigv4 (1.0.0)
    bcrypt (3.1.11)
    builder (3.2.2)
    byebug (9.0.6)
    capybara (2.10.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    carrierwave (0.11.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
      mimemagic (>= 0.3.0)
    coderay (1.1.1)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.11.1)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.1)
    debug_inspector (0.0.2)
    devise (4.2.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    docile (1.1.5)
    doorkeeper (4.2.0)
      railties (>= 4.2)
    erubis (2.7.0)
    excon (0.53.0)
    execjs (2.7.0)
    factory_girl (4.7.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.7.0)
      factory_girl (~> 4.7.0)
      railties (>= 3.0.0)
    faker (1.6.6)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.14)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.38.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-cloudatcost (~> 0.1.0)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-openstack
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-rackspace
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-vsphere (>= 0.4.0)
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.12.0)
      fog-core (~> 1.38)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.11.0)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-cloudatcost (0.1.2)
      fog-core (~> 1.36)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.43.0)
      builder
      excon (~> 0.49)
      formatador (~> 0.2)
    fog-dynect (0.0.3)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.3.0)
      fog-core (~> 1.27)
    fog-openstack (0.1.13)
      fog-core (>= 1.40)
      fog-json (>= 1.0)
      ipaddress (>= 0.8)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (2.0.1)
      fog-core (~> 1.42)
      fog-json (~> 1.0)
    fog-rackspace (0.1.1)
      fog-core (>= 1.35)
      fog-json (>= 1.0)
      fog-xml (>= 0.1)
      ipaddress (>= 0.8)
    fog-radosgw (0.0.5)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.7.5)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.1.4)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-vsphere (1.2.0)
      fog-core
      rbvmomi (~> 1.8.0)
    fog-xenserver (0.2.3)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.7.0.0)
      railties (>= 3.2, < 5.1)
    foreman (0.82.0)
      thor (~> 0.19.1)
    formatador (0.2.5)
    friendly_id (5.2.0)
      activerecord (>= 4.0.0)
    gaffe (1.2.0)
      rails (>= 4.0.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    graphiql-rails (1.4.0)
      rails
    graphql (1.2.5)
    graphql-client (0.3.0)
      activesupport (>= 3.0, < 6.0)
      graphql (>= 0.19.2)
    guard (2.14.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    haml (4.0.7)
      tilt
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.3)
    jmespath (1.3.1)
    jquery-rails (4.2.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (2.0.2)
    jwt (1.5.6)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    libv8 (3.16.14.15)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_magick (4.5.1)
    mini_portile2 (2.1.0)
    minitest (5.9.1)
    monetize (1.4.0)
      money (~> 6.7)
    money (6.7.1)
      i18n (>= 0.6.4, <= 0.7.0)
      sixarm_ruby_unaccent (>= 1.1.1, < 2)
    money-rails (1.7.0)
      activesupport (>= 3.0)
      monetize (~> 1.4.0)
      money (~> 6.7)
      railties (>= 3.0)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mustermann (1.0.0.beta2)
    nenv (0.3.0)
    nested_form (0.3.2)
    nio4r (1.2.1)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    orm_adapter (0.5.0)
    paper_trail (4.2.0)
      activerecord (>= 3.0, < 6.0)
      activesupport (>= 3.0, < 6.0)
      request_store (~> 1.1)
    pg (0.19.0)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (3.6.2)
    pundit (1.1.0)
      activesupport (>= 3.0.0)
    rack (2.0.1)
    rack-cors (0.4.0)
    rack-pjax (1.0.0)
      nokogiri (~> 1.5)
      rack (>= 1.1)
    rack-protection (2.0.0.beta2)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.0.1)
      actioncable (= 5.0.0.1)
      actionmailer (= 5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      activemodel (= 5.0.0.1)
      activerecord (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.1)
      sprockets-rails (>= 2.0.0)
    rails-controller-testing (1.0.1)
      actionpack (~> 5.x)
      actionview (~> 5.x)
      activesupport (~> 5.x)
    rails-dom-testing (2.0.1)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6.0)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_admin (1.1.0)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (>= 0.7)
      rails (>= 4.0, < 6)
      remotipart (~> 1.3)
      sass-rails (>= 4.0, < 6)
    railties (5.0.0.1)
      actionpack (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.1.0)
    rake (11.3.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rbvmomi (1.8.2)
      builder
      nokogiri (>= 1.4.1)
      trollop
    react_on_rails (6.2.1)
      addressable
      connection_pool
      execjs (~> 2.5)
      foreman
      rails (>= 3.2)
      rainbow (~> 2.1)
    redcarpet (3.3.4)
    redis (3.3.2)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    ref (2.0.0)
    request_store (1.3.1)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    retries (0.0.5)
    rollbar (2.13.3)
      multi_json
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    ruby_dep (1.4.0)
    sass (3.4.22)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    shellany (0.0.1)
    simple-random (1.0.3)
    simplecov (0.12.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (2.0.0.beta2)
      mustermann (= 1.0.0.beta2)
      rack (~> 2.0)
      rack-protection (= 2.0.0.beta2)
      tilt (~> 2.0)
    sixarm_ruby_unaccent (1.1.1)
    slop (3.6.0)
    split (2.2.0)
      redis (>= 2.1)
      simple-random (>= 0.9.3)
      sinatra (>= 1.2.6)
    spring (2.0.0)
      activesupport (>= 4.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.5)
    trollop (2.1.2)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.4)
      execjs (>= 0.3.0, < 3)
    warden (1.2.6)
      rack (>= 1.0)
    web-console (3.3.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      debug_inspector
      railties (>= 5.0)
    websocket-driver (0.6.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xml-simple (1.1.5)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  acts_as_list (~> 0.8.2)
  attribute_normalizer (~> 1.2)
  awesome_print
  aws-sdk (= 2.6.30)
  bcrypt (~> 3.1.7)
  byebug
  capybara (= 2.10.0)
  carrierwave (~> 0.11.0)
  devise (~> 4.2)
  doorkeeper (~> 4.1)
  factory_girl_rails (~> 4.6)
  faker (~> 1.6, >= 1.6.3)
  fog (~> 1.38)
  friendly_id (= 5.2.0)
  gaffe (~> 1.2)
  graphiql-rails (= 1.4)
  graphql (= 1.2.5)
  graphql-client (~> 0.3.0)
  guard-rspec (~> 4.6, >= 4.6.5)
  mini_magick (~> 4.5, >= 4.5.1)
  money-rails (~> 1.7)
  oauth2 (~> 1.1)
  paper_trail (~> 4.1)
  pg (~> 0.15)
  puma (= 3.6.2)
  pundit (~> 1.1)
  rack-cors (~> 0.4.0)
  rack-utm_cookies!
  rails (= 5.0.0.1)
  rails-controller-testing (~> 1.0, >= 1.0.1)
  rails_admin (= 1.1.0)
  react_on_rails (= 6.2.1)
  redcarpet (~> 3.3, >= 3.3.4)
  redis-namespace (= 1.5.2)
  remotipart!
  retries (~> 0.0.5)
  rollbar (= 2.13.3)
  rspec-mocks (~> 3.5)
  rspec-rails (= 3.5.2)
  sass-rails (~> 5.0)
  simplecov (= 0.12.0)
  sinatra (~> 2.0.0.beta2)
  split (~> 2.2.0)
  spring
  spring-commands-rspec (~> 1.0, >= 1.0.4)
  therubyracer
  uglifier (= 3.0.4)
  web-console (= 3.3.1)
  with_model!

BUNDLED WITH
   1.13.6
```
</details>

### Example stacktraces:

```
backend_1      | Started GET "/ab" for 172.18.0.3 at 2016-12-01 05:42:33 +0000
backend_1      | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
backend_1      |   User Load (10.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 35], ["LIMIT", 1]]
backend_1      | 2016-12-01 05:42:34 - NameError - uninitialized constant Split::Redis:
backend_1      | 	/bundle/gems/split-2.2.0/lib/split.rb:36:in `redis='
backend_1      | 	/bundle/gems/split-2.2.0/lib/split.rb:51:in `redis'
backend_1      | 	/bundle/gems/split-2.2.0/lib/split/experiment_catalog.rb:7:in `all'
backend_1      | 	/bundle/gems/split-2.2.0/lib/split/experiment_catalog.rb:12:in `all_active_first'
backend_1      | 	/bundle/gems/split-2.2.0/lib/split/dashboard.rb:20:in `block in <class:Dashboard>'
backend_1      | 	/bundle/gems/sinatra-2.0.0.beta2/lib/sinatra/base.rb:1643:in `call'
backend_1      | 	/bundle/gems/sinatra-2.0.0.beta2/lib/sinatra/base.rb:1643:in `block in compile!'
...
...
```

and

```
<ActionView::Template::Error: uninitialized constant Split::Helper::Redis>
/bundle/gems/split-2.2.0/lib/split/helper.rb:21:in `rescue in ab_test'
/bundle/gems/split-2.2.0/lib/split/helper.rb:31:in `ab_test'
/app/app/views/deals/dropsuite_show.html.erb:43:in `_app_views_deals_dropsuite_show_html_erb___3250229126497424756_47238656436360'
/bundle/gems/actionview-5.0.0.1/lib/action_view/template.rb:158:in `block in render'
/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/bundle/gems/actionview-5.0.0.1/lib/action_view/template.rb:348:in `instrument'
/bundle/gems/actionview-5.0.0.1/lib/action_view/template.rb:156:in `render'
/bundle/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/bundle/gems/actionview-5.0.0.1/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
```

**Comment by tomciopp** [comment]
@joffotron I ran into the same issue, however after doing some digging, adding `redis-namespace` is a red herring. The actual problem is that `redis` itself has not been required. If you add the following line to the top of `config/initializers/split.rb` you should be fine.

    require "redis"

    Split.configure do |config|
      ...
    end
